name       : perl-net-ssleay
version    : '1.92'
release    : 17
source     :
    - https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.92.tar.gz : 47c2f2b300f2e7162d71d699f633dd6a35b0625a00cbda8c50ac01144a9396a9
homepage   : https://metacpan.org/pod/Net::SSLeay
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : Net::SSLeay - Perl extension for using OpenSSL
description: |
    This module provides Perl bindings for libssl (an SSL/TLS API) and libcrypto (a cryptography API).
builddeps  :
    - perl-test-exception
    - perl-test-nowarnings
    - perl-test-pod
    - perl-test-simple
    - perl-test-warn
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
