name       : perl-net-ssleay
version    : '1.85'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.85.tar.gz : 9d8188b9fb1cae3bd791979c20554925d5e94a138d00414f1a6814549927b0c8
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : Net::SSLeay - Perl extension for using OpenSSL
description: |
    Net::SSLeay - Perl extension for using OpenSSL
builddeps  :
    - pkgconfig(libssl)
    - perl-test-exception
    - perl-test-nowarnings
    - perl-test-pod
    - perl-test-simple
    - perl-test-warn
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
