name       : perl-net-ssleay
version    : '1.84'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/M/MI/MIKEM/Net-SSLeay-1.84.tar.gz : 823ec3cbb428309d6a9e56f362a9300693ce3215b7fede109adb7be361fff177
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : Net::SSLeay - Perl extension for using OpenSSL
description: |
    Net::SSLeay - Perl extension for using OpenSSL
builddeps  :
    - pkgconfig(libssl)
    - perl-io
    - perl-test-pod
    - perl-test-simple
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
