name        : perl-net-ssleay
version     : 1.74
release     : 4
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MI/MIKEM/Net-SSLeay-1.74.tar.gz : 167a955410168a6d617fbb11d8a40a5ebffaef950035fb072b3e9b6b706cbc7d
license     :
    - Artistic-Perl-1.0
summary     : Net::SSLeay - Perl extension for using OpenSSL
component   : programming.perl
builddeps   :
    - pkgconfig(libssl)
    - perl
    - perl-io
description : |
    Net::SSLeay - Perl extension for using OpenSSL
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
