name       : perl-net-ssleay
version    : '1.80'
release    : 5
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MI/MIKEM/Net-SSLeay-1.80.tar.gz : a541a66d59fc5f9bb7af09d3a0b68305e4c43ba9488b12915728fd282ea01b93
license    :
    - Artistic-Perl-1.0
summary    : Net::SSLeay - Perl extension for using OpenSSL
component  : programming.perl
builddeps  :
    - pkgconfig(libssl)
    - perl
    - perl-io
description: |
    Net::SSLeay - Perl extension for using OpenSSL
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
