name       : perl-net-ssleay
version    : '1.88'
release    : 11
source     :
    - https://cpan.metacpan.org/authors/id/C/CH/CHRISN/Net-SSLeay-1.88.tar.gz : 2000da483c8471a0b61e06959e92a6fca7b9e40586d5c828de977d3d2081cfdd
license    : Artistic-Perl-2.0
component  : programming.perl
summary    : Net::SSLeay - Perl extension for using OpenSSL
description: |
    Net::SSLeay - Perl extension for using OpenSSL
builddeps  :
    - perl-test-exception
    - perl-test-nowarnings
    - perl-test-pod
    - perl-test-simple
    - perl-test-warn
setup      : |
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
